apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: selenium-hub
  name: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: selenium-hub
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: selenium-hub
    spec:
      containers:
        - env:
            - name: SE_GRID_MAX_SESSION
              value: "10"
          image: selenium/hub:4.4.0-20220831
          name: selenium-hub
          ports:
            - containerPort: 4442
            - containerPort: 4443
            - containerPort: 4444
          resources: {}
      restartPolicy: Always
status: {}
